CXX=g++
CXXFLAGS=-Wall -Werror -std=c++11

all: $(patsubst %.cpp, $(TARGET_DIR)%.o, $(wildcard *.cpp))

$(ASD)%.o: %.cpp Makefile
	$(CXX) $(CXXFLAGS) $< -o $(@:.o=)

clean: $(patsubst %.cpp, %.clean, $(wildcard *.cpp))

%.clean:
	rm -f $(@:.clean=)