/**
 * Created by adamellis on 06/02/2017.
 */
(function(){
    angular.module('PeerFeedback',['ui.router'])
        .config(function($stateProvider,$urlRouterProvider){
            $stateProvider
                .state('frameState',{
                    url:'/frame',
                    templateUrl:'app/frame/frame.html',
                    controller:'frameController'
                })
                .state('frameState.configurationState',{
                    url:'/configuration?aid',
                    templateUrl:'app/configuration/configuration.html',
                    controller:'configurationController'
                })
                .state('frameState.providerState',{
                    url:'/provider?sid?aid?studentuid',
                    templateUrl:'app/provider/provider.html',
                    controller:'providerController'
                })
                .state('frameState.adminState',{
                    url:'/admin?studentuid',
                    templateUrl:'app/admin/admin.html',
                    controller:'adminController'
                })
                .state('frameState.receiverState',{
                    url:'/receiver?sid?studentuid',
                    templateUrl:'app/receiver/receiver.html',
                    controller:'receiverController'
                })
                .state('frameState.responseState',{
                    url:'/response',
                    templateUrl:'app/response/response.html',
                    controller:'responseController'
                });
                $urlRouterProvider.otherwise('/frame');
        });
}());