/**
 * Created by adamellis on 06/02/2017.
 */
(function(){
    angular.module('PeerFeedback',['ui.router'])
        .config(function($stateProvider,$urlRouterProvider){
            $stateProvider
                .state('frameState',{
                    url:'/frame',
                    templateUrl:'app/frame/frame.html',
                    controller:'frameController'
                })
                .state('frameState.allocationState',{
                    url:'/allocation?sid',
                    templateUrl:'app/allocation/allocation.html',
                    controller:'allocationController'
                })
                .state('frameState.configurationState',{
                    url:'/configuration?aid',
                    templateUrl:'app/configuration/configuration.html',
                    controller:'configurationController'
                })
                .state('frameState.providerState',{
                    url:'/provider',
                    params:{
                        aid:null,
                        providersid:null,
                        sid:null
                    },
                    templateUrl:'app/provider/provider.html',
                    controller:'providerController'
                })
                .state('frameState.receiverState',{
                    url:'/receiver',
                    params:{
                        aid:null,
                        providersid:null,
                        sid:null
                    },
                    templateUrl:'app/receiver/receiver.html',
                    controller:'receiverController'
                });
                $urlRouterProvider.otherwise('/frame');
        });
}());