# Configuration for sneakers per environment
# AMQP URL will be constructed from environment variables in any case

development:
  exchange: sneakers
  exchange_type: direct
  durable: true
  ack: true

production:
  exchange: sneakers
  exchange_type: direct
  durable: true
  ack: true
  daemonize: true        # Send to background
  log: sneakers.log      # Log file
  pid_path: sneakers.pid # Pid file

test:
  exchange: sneakers
  exchange_type: direct
  durable: true
  ack: true
